# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA_HLS/Basic_Output/Vivado/basicOutput_HW.srcs/sources_1/bd/basicOutput/ip/basicOutput_basic_output_0_0/basicOutput_basic_output_0_0.xci
# IP: The module: 'basicOutput_basic_output_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HLS/Basic_Output/Vivado/basicOutput_HW.gen/sources_1/bd/basicOutput/ip/basicOutput_basic_output_0_0/constraints/basic_output_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'basicOutput_basic_output_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FPGA_HLS/Basic_Output/Vivado/basicOutput_HW.srcs/sources_1/bd/basicOutput/ip/basicOutput_basic_output_0_0/basicOutput_basic_output_0_0.xci
# IP: The module: 'basicOutput_basic_output_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HLS/Basic_Output/Vivado/basicOutput_HW.gen/sources_1/bd/basicOutput/ip/basicOutput_basic_output_0_0/constraints/basic_output_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'basicOutput_basic_output_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
