# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA_HLS/Trafic_Lights/Vivado/traficLights.srcs/sources_1/bd/traficLight/ip/traficLight_traficLights_0_0/traficLight_traficLights_0_0.xci
# IP: The module: 'traficLight_traficLights_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HLS/Trafic_Lights/Vivado/traficLights.gen/sources_1/bd/traficLight/ip/traficLight_traficLights_0_0/constraints/traficLights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'traficLight_traficLights_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FPGA_HLS/Trafic_Lights/Vivado/traficLights.srcs/sources_1/bd/traficLight/ip/traficLight_traficLights_0_0/traficLight_traficLights_0_0.xci
# IP: The module: 'traficLight_traficLights_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HLS/Trafic_Lights/Vivado/traficLights.gen/sources_1/bd/traficLight/ip/traficLight_traficLights_0_0/constraints/traficLights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'traficLight_traficLights_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
