# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/basicOutput/basicOutput.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basicOutput || ORIG_REF_NAME==basicOutput} -quiet] -quiet

# IP: bd/basicOutput/ip/basicOutput_basic_output_0_0/basicOutput_basic_output_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basicOutput_basic_output_0_0 || ORIG_REF_NAME==basicOutput_basic_output_0_0} -quiet] -quiet

# XDC: d:/FPGA_HLS/Basic_Output/Vivado/basicOutput_HW.gen/sources_1/bd/basicOutput/basicOutput_ooc.xdc
