# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/traficLight/traficLight.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==traficLight || ORIG_REF_NAME==traficLight} -quiet] -quiet

# IP: bd/traficLight/ip/traficLight_traficLights_0_0/traficLight_traficLights_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==traficLight_traficLights_0_0 || ORIG_REF_NAME==traficLight_traficLights_0_0} -quiet] -quiet

# XDC: d:/FPGA_HLS/Trafic_Lights/Vivado/traficLights.gen/sources_1/bd/traficLight/traficLight_ooc.xdc
