# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/basicInputOutput/basicInputOutput.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basicInputOutput || ORIG_REF_NAME==basicInputOutput} -quiet] -quiet

# IP: bd/basicInputOutput/ip/basicInputOutput_basicInputOutput_0_0/basicInputOutput_basicInputOutput_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basicInputOutput_basicInputOutput_0_0 || ORIG_REF_NAME==basicInputOutput_basicInputOutput_0_0} -quiet] -quiet

# XDC: d:/FPGA_HLS/Basic_Input_Output/Vivado/basicInputOutput.gen/sources_1/bd/basicInputOutput/basicInputOutput_ooc.xdc
